//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidTracer.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CovidTracer.Resx.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AboutTracerKey {
            get {
                return ResourceManager.GetString("AboutTracerKey", resourceCulture);
            }
        }
        
        public static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        public static string AboutIcons {
            get {
                return ResourceManager.GetString("AboutIcons", resourceCulture);
            }
        }
        
        public static string AboutFreeSoftware {
            get {
                return ResourceManager.GetString("AboutFreeSoftware", resourceCulture);
            }
        }
        
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        public static string DetailsNoInteraction {
            get {
                return ResourceManager.GetString("DetailsNoInteraction", resourceCulture);
            }
        }
        
        public static string DetailsInteractionPositiveTitle {
            get {
                return ResourceManager.GetString("DetailsInteractionPositiveTitle", resourceCulture);
            }
        }
        
        public static string DetailsInteractionPositiveDetails {
            get {
                return ResourceManager.GetString("DetailsInteractionPositiveDetails", resourceCulture);
            }
        }
        
        public static string DetailsInteractionSymptomaticTitle {
            get {
                return ResourceManager.GetString("DetailsInteractionSymptomaticTitle", resourceCulture);
            }
        }
        
        public static string DetailsInteractionSymptomaticDetails {
            get {
                return ResourceManager.GetString("DetailsInteractionSymptomaticDetails", resourceCulture);
            }
        }
        
        public static string DetailsInteractionHistoryDate {
            get {
                return ResourceManager.GetString("DetailsInteractionHistoryDate", resourceCulture);
            }
        }
        
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        public static string MainAboutButton {
            get {
                return ResourceManager.GetString("MainAboutButton", resourceCulture);
            }
        }
        
        public static string MainDetailsButton {
            get {
                return ResourceManager.GetString("MainDetailsButton", resourceCulture);
            }
        }
        
        public static string MainSignalingButton {
            get {
                return ResourceManager.GetString("MainSignalingButton", resourceCulture);
            }
        }
        
        public static string MainPrivacyDetails {
            get {
                return ResourceManager.GetString("MainPrivacyDetails", resourceCulture);
            }
        }
        
        public static string MainStatusSafeTitle {
            get {
                return ResourceManager.GetString("MainStatusSafeTitle", resourceCulture);
            }
        }
        
        public static string MainStatusSafeText {
            get {
                return ResourceManager.GetString("MainStatusSafeText", resourceCulture);
            }
        }
        
        public static string MainStatusSymptomaticTitle {
            get {
                return ResourceManager.GetString("MainStatusSymptomaticTitle", resourceCulture);
            }
        }
        
        public static string MainStatusSymptomaticText {
            get {
                return ResourceManager.GetString("MainStatusSymptomaticText", resourceCulture);
            }
        }
        
        public static string MainStatusPositiveTitle {
            get {
                return ResourceManager.GetString("MainStatusPositiveTitle", resourceCulture);
            }
        }
        
        public static string MainStatusPositiveText {
            get {
                return ResourceManager.GetString("MainStatusPositiveText", resourceCulture);
            }
        }
        
        public static string OnboardingContinue {
            get {
                return ResourceManager.GetString("OnboardingContinue", resourceCulture);
            }
        }
        
        public static string OnboardingBluetooth {
            get {
                return ResourceManager.GetString("OnboardingBluetooth", resourceCulture);
            }
        }
        
        public static string OnboardingPrivacy {
            get {
                return ResourceManager.GetString("OnboardingPrivacy", resourceCulture);
            }
        }
        
        public static string OnboardingRecommendedUses {
            get {
                return ResourceManager.GetString("OnboardingRecommendedUses", resourceCulture);
            }
        }
        
        public static string SignalingTitle {
            get {
                return ResourceManager.GetString("SignalingTitle", resourceCulture);
            }
        }
        
        public static string SignalingNotice {
            get {
                return ResourceManager.GetString("SignalingNotice", resourceCulture);
            }
        }
        
        public static string SignalingFormSymptomsOnset {
            get {
                return ResourceManager.GetString("SignalingFormSymptomsOnset", resourceCulture);
            }
        }
        
        public static string SignalingFormIsTested {
            get {
                return ResourceManager.GetString("SignalingFormIsTested", resourceCulture);
            }
        }
        
        public static string SignalingFormComment {
            get {
                return ResourceManager.GetString("SignalingFormComment", resourceCulture);
            }
        }
        
        public static string SignalingFormSubmit {
            get {
                return ResourceManager.GetString("SignalingFormSubmit", resourceCulture);
            }
        }
    }
}
